[package]
name = "vulkano_experiments"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 1

[dependencies]
# engine
flecs_ecs = "0.1.3"
# renet = "1.0.0"
# graphical
vulkano = "0.35.0"
vulkano-shaders = "0.35.0"
vulkano-util = "0.35.0"
winit = "0.30"